const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';

const USER_NAME_ALREADY_EXISTS = 'USER_NAME_ALREADY_EXISTS';

const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS';

const USER_NAME_OR_PASSWORD_ERROR = 'USER_NAME_OR_PASSWORD_ERROR';

const UNAUTHORIZED = 'UNAUTHORIZED';

const UNPERMISSION = 'UNPERMISSION';

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  USER_NAME_ALREADY_EXISTS,
  USER_DOES_NOT_EXISTS,
  USER_NAME_OR_PASSWORD_ERROR,
  UNAUTHORIZED,
  UNPERMISSION
}