const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';

const USER_NAME_ALREADY_EXISTS = 'USER_NAME_ALREADY_EXISTS';

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  USER_NAME_ALREADY_EXISTS
}